#!/bin/bash
##############################################################################
#
# MailWatch for MailScanner
# Copyright (C) 2003-2011  Steve Freegard (steve@freegard.name)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
##############################################################################
#
# File:		fix_quarantine_permissions
#
# Purpose:	Loosen quarantine permissions sufficiently to allow MailWatch
#		to release/learn/delete message contained within.
#
# Usage:	You should edit the variables below to suit your configuration
#		and run this script from cron every minute.
#
##############################################################################

# Variables
QUARANTINEDIR="/var/spool/MailScanner/quarantine"
DIRMODE=0770	# drwxrwx---
FILEMODE=0660	# -rw-rw----
GROUP=www-data	# Should be the same group as the web server

# Directories
find /var/spool/MailScanner/quarantine -type d \( \! -group $GROUP -o -type d \! -perm $DIRMODE \) -print | while read DIR;
do
 chmod $DIRMODE "$DIR"
 chown :$GROUP "$DIR" 
done

# Files
find /var/spool/MailScanner/quarantine -type f \( \! -group $GROUP -o \! -perm $FILEMODE \) -print | while read FILE;
do
 chmod $FILEMODE "$FILE"
 chown :$GROUP "$FILE"
done
