#!/bin/bash

# MailWatch for MailScanner
# Copyright (C) 2003-2011  Steve Freegard (steve@freegard.name)
# Copyright (C) 2011  Garrod Alwood (garrod.alwood@lorodoes.com)
# Copyright (C) 2014-2017  MailWatch Team (https://github.com/mailwatch/1.2.0/graphs/contributors)

test -x /var/www/html/mailscanner/postfix_relay.php || exit 0
/usr/bin/php -q /var/www/html/mailscanner/postfix_relay.php --refresh

test -x /var/www/html/mailscanner/mailscanner_relay.php || exit 0
/usr/bin/php -q /var/www/html/mailscanner/mailscanner_relay.php --refresh

exit 0
