name: Format (PHP)

on:
  pull_request:
    branches: [ "1.3" ]
    paths:
      - '**/*.php'
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v4"

      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --allow-risky=yes
